### ISSUE TITLE
A failure occurred in package_linux516-tkg-bmq-headers()

### ISSUE THREAD

**Issue by Shadow12347** [Frogging-Family/linux-tkg#409]
I've been able to compile the kernel many times across many different versions, and I am now trying to compile 5.16. It runs through everything like normal but fails every time near the end with this error:

> ==> Starting package_linux516-tkg-bmq-headers()...
>   -> Installing build files...
> **install: cannot stat 'tools/bpf/resolve_btfids/resolve_btfids': No such file or directory**
> ==> ERROR: A failure occurred in package_linux516-tkg-bmq-headers().

I tried across commits and still am not able to get past this issue on 5.16, while 5.15 works just fine. I'm using gcc with -O3 and ZEN3 (which has never caused an issue for me).

OS: Manjaro KDE Plasma
CPU: Ryzen 9 5950x

**Comment by Shadow12347** [comment]
I was able to resolve this by commenting this line out in the PKGBUILD:

> #install -Dt "$builddir"/tools/bpf/resolve_btfids tools/bpf/resolve_btfids/resolve_btfids

I then received some errors about winesync files being in conflict with my 5.15 tkg install. So I rebooted into a stock kernel, uninstalled 5.15 tkg, and then installed 5.16 tkg, which is now running successfully.

**Comment by AdelKS** [comment]
This issue should be fixed as that line you commented out is only run on 5.16+

**Comment by Shadow12347** [comment]
I'm compiling 5.16 (and running 5.16), and I am still receiving this error. But commenting out the if statement for btfids resolves it.

**Comment by AdelKS** [comment]
I see, does it happen with other schedulers for example ? Something is off as you seem to be the only one who has this issue ?

**Comment by Shadow12347** [comment]
Yeah, I have a cacule version alongside the bmq one that I used for testing, and it happens on both. That said, if it isn't affecting anyone else, I already found a workaround, and it shouldn't be an issue once I move to 5.17.

**Comment by Shadow12347** [comment]
I think I figured this out. Per https://wiki.archlinux.org/title/NVIDIA#Custom_kernel:

> Ensure your kernel config has CONFIG_DRM_SIMPLEDRM=y, **and if using CONFIG_DEBUG_INFO_BTF then this is needed in the PKGBUILD (since kernel 5.16):**
> 
> ```
> install -Dt "$builddir/tools/bpf/resolve_btfids" tools/bpf/resolve_btfids/resolve_btfids`
> ```


CONFIG_DEBUG_INFO_BTF depends on CONFIG_DEBUG_INFO, which is disabled with the customization.cfg option:

```
_debugdisable="true"
```

For that reason, if this is set to true, resolve_btfids is not included, which explains why it can't find the file.

I tried re-compiling with this set to false instead (and verifying that both of these were enabled), as well as after un-commenting the if statement in the PKGBUILD, and I was able to compile successfully.

It would seem that additional checks are needed in the if statement to not try and install resolve_btfids when debugging is disabled. 

I tested this by re-compiling after setting this back to true (verifying that CONFIG_DEBUG_INFO is N), and modifying the PKGBUILD as such:

```
  # add resolve_btfids on 5.16+ when debugging is also enabled
  if [ $_debugdisable != "true" ] && [ $_basever -ge 516 ]; then
    install -Dt "$builddir"/tools/bpf/resolve_btfids tools/bpf/resolve_btfids/resolve_btfids
  fi
```
Which successfully allowed me to compile 5.16.10 with debugging disabled. After actually looking into this, I believe this would be a problem for anyone with this setting on 5.16+ without modifying the PKGBUILD with something along these lines.

**Comment by TheLiberaceSequence** [comment]
It's not a scheduler issue. You have some part of the bpf framework enabled that requires the btf info, but the kernel is compiled without the said info. 

For the 'resolve_btfids' tool to work, the kernel needs to be compiled with 'DEBUG_INFO_BTF=y'.

> CONFIG_DEBUG_INFO_BTF:
> 
> Generate deduplicated BTF type information from DWARF debug info.
> Turning this on expects presence of pahole tool, which will convert
> DWARF type info into equivalent deduplicated BTF type info.
> 
> Symbol: DEBUG_INFO_BTF [=y]
> Type : bool
> Defined at lib/Kconfig.debug:315
> Prompt: Generate BTF typeinfo
> Depends on: DEBUG_INFO [=y] && !DEBUG_INFO_SPLIT [=n] && !DEBUG_INFO_REDUCED [=n] && (!GCC_PLUGIN_RANDSTRUCT [=n] || COMPILE_TEST [=n]) && BPF_SYSCALL [=y]
> Location:
> Main menu
> -> Kernel hacking
> -> Compile-time checks and compiler options
> -> Compile the kernel with debug info (DEBUG_INFO [=y])
>
