### ISSUE TITLE
Error applying patch for 6.1.9

### ISSUE THREAD

**Issue by Flenzak** [Frogging-Family/linux-tkg#704]
Make failure 
 make[4]: *** [scripts/Makefile.build:500: drivers] Error 2
make[3]: *** [Makefile:2005: .] Error 2
make[2]: *** [debian/rules:7: build-arch] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
make[1]: *** [scripts/Makefile.package:80: deb-pkg] Error 2
make: *** [Makefile:1649: deb-pkg] Error 2
 -> exit cleanup done

Debian Bookworm
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/10558185/system-info.txt)

[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/10558189/prepare.log.txt)
[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/10558190/customization.cfg.txt)

 Looking at prepare.log the first issue seems to be with drivers/gpu/drm/amd/display/amdgpu_dm/amdgpu_dm_helpers.c
Hunk #2 FAILED at 119

As a side note I have run this on 6.1.7 without issues

**Comment by Tk-Glitch** [comment]
This was fixed with https://github.com/Frogging-Family/linux-tkg/commit/3fd1eaddc4b8de0107ede10abab0b9db21f5654c a few hours ago. A pull should get you back on track.

**Comment by Flenzak** [comment]
Sorry to say this issue is still happening on 6.1.9 and 6.1.10 .

**Comment by Flenzak** [comment]
I dont know this is by design or a bug but I just deleted the whole linux-tkg directory tree and installed from scratch and I have compiled 6.1.11 perfectly with no issues.
