### ISSUE TITLE
Cannot install on Fedora 39

### ISSUE THREAD

**Issue by Exotic0015** [Frogging-Family/linux-tkg#822]
Installing the output RPMs on Fedora 39 Prerelease results in the following error:
```
grub2-mkrelpath: error: failed to get canonical path of `/boot/vmlinuz-6.5.5_tkg_bore_eevdf'.
dirname: missing operand
Try 'dirname --help' for more information.
```
Also, vmlinuz is missing from the /boot partition.

~~Could possibly be related to the recent release of [RPM 4.19.0](http://rpm.org/wiki/Releases/4.19.0) which is already included in the prerelease.~~
It is caused by */sbin/installkernel* being moved from grubby to systemd-udev's */usr/bin/kernel-install* behind a compatibility layer and the layer somehow failing, hence the kernel install script failure

[Related RedHat bugzilla bug](https://bugzilla.redhat.com/show_bug.cgi?id=2239008)
[Another RedHat bugzilla bug](https://bugzilla.redhat.com/show_bug.cgi?id=2244131)
[Related systemd issue](https://github.com/systemd/systemd/issues/29568)

**Comment by xezrunner** [comment]
Can confirm, still happening on Fedora 39 Prerelease.

After the script does finish, the GRUB entry for the kernel does not work.

**Comment by Everest10** [comment]
![image](https://github.com/Frogging-Family/linux-tkg/assets/7228207/0e7b45a4-c880-4fc6-a21e-9e5b08598a43)

Same problem here at fedora 39 not generating vmlinuz-6.5.6_tkg_pds

[customization.cfg.txt](https://github.com/Frogging-Family/linux-tkg/files/12836850/customization.cfg.txt)
[prepare.log.txt](https://github.com/Frogging-Family/linux-tkg/files/12836851/prepare.log.txt)
[shell-output.log.txt](https://github.com/Frogging-Family/linux-tkg/files/12836852/shell-output.log.txt)
[system-info.txt](https://github.com/Frogging-Family/linux-tkg/files/12836853/system-info.txt)

**Comment by Exotic0015** [comment]
[Related RedHat bugzilla bug](https://bugzilla.redhat.com/show_bug.cgi?id=2239008)

**Comment by Exotic0015** [comment]
Supposedly fixed with [grub2-2.06-103.fc39](https://bodhi.fedoraproject.org/updates/FEDORA-2023-144afbd4c3)

**Comment by Everest10** [comment]
> Supposedly fixed with [grub2-2.06-103.fc39](https://bodhi.fedoraproject.org/updates/FEDORA-2023-144afbd4c3)

Please merge your answer in one topic.
This solution still not working to me. I have testing repo enable.

The manual solution was extract the kernel.rpm file and copy as root the vmlinuz-6.5.6_tkg_pds into /boot

**Comment by AdelKS** [comment]
Hello, please try #840 and see if that fixes the issue

**Comment by Exotic0015** [comment]
Fixed with #840
